overrides:
  '@riotprompt/riotprompt': link:../../StJustReckoning/riotprompt
  '@theunwalked/cardigantime': link:../../SemicolonAmbulance/cardigantime
  '@theunwalked/dreadcabinet': link:../../SemicolonAmbulance/dreadcabinet
